In [6]:
import numpy as np
import pandas as pd

In [7]:
df=pd.read_excel(r"C:\Users\tanpu\Downloads\data.xlsx")
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [ ]:

print(df.columns)

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [ ]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [ ]:
df_numerical_data=df[['BirthRate','Internetusers']]
df_categorial_data=df[['ContryName,'IncomeGroup']]

In [ ]:
df

In [ ]:
df=pd.read_excel(r"C:\Users\tanpu\Downloads\data.xlsx")
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [8]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [9]:
df[:]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [ ]:
df[10:11]

   CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
10  Azerbaijan         AZE       18.3           58.7  Upper middle income

In [ ]:
df[13:15]

     CountryName CountryCode  BirthRate  InternetUsers IncomeGroup
13         Benin         BEN     36.440            4.9  Low income
14  Burkina Faso         BFA     40.551            9.1  Low income

In [10]:
df[15:20]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
15,Bangladesh,BGD,20.142,6.63000,Lower middle income
16,Bulgaria,BGR,9.200,53.06150,Upper middle income
17,Bahrain,BHR,15.040,90.00004,High income
18,"Bahamas, The",BHS,15.339,72.00000,High income
19,Bosnia and Herzegovina,BIH,9.062,57.79000,Upper middle income

In [11]:
df[0:100:20]

   CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0        Aruba         ABW     10.244          78.90          High income
20     Belarus         BLR     12.500          54.17  Upper middle income
40  Costa Rica         CRI     15.022          45.96  Upper middle income
60       Gabon         GAB     30.555           9.20  Upper middle income
80       India         IND     20.291          15.10  Lower middle income

In [12]:
df[::5]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.900000,High income
5,Argentina,ARG,17.716,59.900000,High income
10,Azerbaijan,AZE,18.300,58.700000,Upper middle income
15,Bangladesh,BGD,20.142,6.630000,Lower middle income
20,Belarus,BLR,12.500,54.170000,Upper middle income
25,Barbados,BRB,12.188,73.000000,High income
30,Canada,CAN,10.900,85.800000,High income
35,Cameroon,CMR,37.236,6.400000,Lower middle income
40,Costa Rica,CRI,15.022,45.960000,Upper middle income
45,Germany,DEU,8.500,84.170000,High income
50,Ecuador,ECU,21.070,40.353684,Upper middle income
55,Ethiopia,ETH,32.925,1.900000,Low income
60,Gabon,GAB,30.555,9.200000,Upper middle income
65,"Gambia, The",GMB,42.525,14.000000,Low income
70,Greenland,GRL,14.500,65.800000,High income
75,Honduras,HND,21.593,17.800000,Lower middle income
80,India,IND,20.291,15.100000,Lower middle income
85,Israel,ISR,21.300,70.800000,High income
90,Kazakhstan,KAZ,22.730,54.000000,Upper middle income
95,"Korea, Rep.",KOR,8.600,84.770000,High income
100,Libya,LBY,21.425,16.500000,Upper middle income
105,Lithuania,LTU,10.100,68.452900,High income
110,Moldova,MDA,12.141,45.000000,Lower middle income
115,Mali,MLI,44.138,3.500000,Low income
120,Mozambique,MOZ,39.705,5.400000,Low income
125,Namibia,NAM,29.937,13.900000,Upper middle income
130,Netherlands,NLD,10.200,93.956400,High income
135,Pakistan,PAK,29.582,10.900000,Lower middle income
140,Poland,POL,9.600,62.849200,High income
145,Qatar,QAT,11.940,85.300000,High income
150,Sudan,SDN,33.477,22.700000,Lower middle income
155,El Salvador,SLV,17.476,23.109300,Lower middle income
160,Suriname,SUR,18.455,37.400000,Upper middle income
165,Seychelles,SYC,18.600,50.400000,High income
170,Tajikistan,TJK,30.792,16.000000,Lower middle income
175,Tunisia,TUN,19.800,43.800000,Upper middle income
180,Uruguay,URY,14.374,57.690000,High income
185,Virgin Islands (U.S.),VIR,10.700,45.300000,High income
190,"Yemen, Rep.",YEM,32.947,20.000000,Lower middle income

In [13]:
df[::-1]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
194,Zimbabwe,ZWE,35.715,18.5,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
191,South Africa,ZAF,20.850,46.5,Upper middle income
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
...,...,...,...,...,...
4,United Arab Emirates,ARE,11.044,88.0,High income
3,Albania,ALB,12.877,57.2,Upper middle income
2,Angola,AGO,45.985,19.1,Upper middle income
1,Afghanistan,AFG,35.253,5.9,Low income
0,Aruba,ABW,10.244,78.9,High income

In [14]:
df[::10]

     CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0          Aruba         ABW     10.244      78.900000          High income
10    Azerbaijan         AZE     18.300      58.700000  Upper middle income
20       Belarus         BLR     12.500      54.170000  Upper middle income
30        Canada         CAN     10.900      85.800000          High income
40    Costa Rica         CRI     15.022      45.960000  Upper middle income
50       Ecuador         ECU     21.070      40.353684  Upper middle income
60         Gabon         GAB     30.555       9.200000  Upper middle income
70     Greenland         GRL     14.500      65.800000          High income
80         India         IND     20.291      15.100000  Lower middle income
90    Kazakhstan         KAZ     22.730      54.000000  Upper middle income
100        Libya         LBY     21.425      16.500000  Upper middle income
110      Moldova         MDA     12.141      45.000000  Lower middle income
120   Mozambique         MOZ     39.705       5.400000           Low income
130  Netherlands         NLD     10.200      93.956400          High income
140       Poland         POL      9.600      62.849200          High income
150        Sudan         SDN     33.477      22.700000  Lower middle income
160     Suriname         SUR     18.455      37.400000  Upper middle income
170   Tajikistan         TJK     30.792      16.000000  Lower middle income
180      Uruguay         URY     14.374      57.690000          High income
190  Yemen, Rep.         YEM     32.947      20.000000  Lower middle income

In [15]:
df[::-5]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
194,Zimbabwe,ZWE,35.715,18.5000,Low income
189,Samoa,WSM,26.172,15.3000,Lower middle income
184,"Venezuela, RB",VEN,19.842,54.9000,High income
179,Ukraine,UKR,11.100,41.0000,Lower middle income
174,Trinidad and Tobago,TTO,14.590,63.8000,High income
169,Thailand,THA,11.041,28.9400,Upper middle income
164,Swaziland,SWZ,30.093,24.7000,Lower middle income
159,Sao Tome and Principe,STP,34.537,23.0000,Lower middle income
154,Sierra Leone,SLE,36.729,1.7000,Low income
149,Saudi Arabia,SAU,20.576,60.5000,High income
144,French Polynesia,PYF,16.393,56.8000,High income
139,Papua New Guinea,PNG,28.899,6.5000,Lower middle income
134,Oman,OMN,20.419,66.4500,High income
129,Nicaragua,NIC,20.788,15.5000,Lower middle income
124,Malaysia,MYS,16.805,66.9700,Upper middle income
119,Mongolia,MNG,24.275,20.0000,Upper middle income
114,"Macedonia, FYR",MKD,11.222,65.2400,Upper middle income
109,Morocco,MAR,21.023,56.0000,Lower middle income
104,Lesotho,LSO,28.738,5.0000,Lower middle income
99,Liberia,LBR,35.521,3.2000,Low income
94,Kiribati,KIR,29.044,11.5000,Lower middle income
89,Japan,JPN,8.200,89.7100,High income
84,Iceland,ISL,13.400,96.5468,High income
79,Indonesia,IDN,20.297,14.9400,Lower middle income
74,"Hong Kong SAR, China",HKG,7.900,74.2000,High income
69,Grenada,GRD,19.334,35.0000,Upper middle income
64,Guinea,GIN,37.337,1.6000,Low income
59,"Micronesia, Fed. Sts.",FSM,23.511,27.8000,Lower middle income
54,Estonia,EST,10.300,79.4000,High income
49,Algeria,DZA,24.738,16.5000,Upper middle income
44,Czech Republic,CZE,10.200,74.1104,High income
39,Cabo Verde,CPV,21.625,37.5000,Lower middle income
34,Cote d'Ivoire,CIV,37.320,8.4000,Lower middle income
29,Central African Republic,CAF,34.076,3.5000,Low income
24,Brazil,BRA,14.931,51.0400,Upper middle income
19,Bosnia and Herzegovina,BIH,9.062,57.7900,Upper middle income
14,Burkina Faso,BFA,40.551,9.1000,Low income
9,Austria,AUT,9.400,80.6188,High income
4,United Arab Emirates,ARE,11.044,88.0000,High income

In [ ]:
df.isnull()

     CountryName  CountryCode  BirthRate  InternetUsers  IncomeGroup  mycalc
0          False        False      False          False        False   False
1          False        False      False          False        False   False
2          False        False      False          False        False   False
3          False        False      False          False        False   False
4          False        False      False          False        False   False
..           ...          ...        ...            ...          ...     ...
190        False        False      False          False        False   False
191        False        False      False          False        False   False
192        False        False      False          False        False   False
193        False        False      False          False        False   False
194        False        False      False          False        False   False

[195 rows x 6 columns]

In [ ]:
df.isna()

     CountryName  CountryCode  BirthRate  InternetUsers  IncomeGroup  mycalc
0          False        False      False          False        False   False
1          False        False      False          False        False   False
2          False        False      False          False        False   False
3          False        False      False          False        False   False
4          False        False      False          False        False   False
..           ...          ...        ...            ...          ...     ...
190        False        False      False          False        False   False
191        False        False      False          False        False   False
192        False        False      False          False        False   False
193        False        False      False          False        False   False
194        False        False      False          False        False   False

[195 rows x 6 columns]

In [ ]:
df.isnull().sum()

CountryName      0
CountryCode      0
BirthRate        0
InternetUsers    0
IncomeGroup      0
mycalc           0
dtype: int64

In [ ]:
df

In [ ]:
df.isnull().sum()

CountryName      0
CountryCode      0
BirthRate        0
InternetUsers    0
IncomeGroup      0
mycalc           0
dtype: int64

In [ ]:
df.describe()

        BirthRate  InternetUsers       mycalc
count  195.000000     195.000000   195.000000
mean    21.469928      42.076471   653.559009
std     10.605467      29.030788   351.553521
min      7.900000       0.900000    28.990400
25%     12.120500      14.520000   361.263300
50%     19.680000      41.000000   682.074300
75%     29.759500      66.225000   892.690170
max     49.661000      96.546800  1552.589500

In [18]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [20]:
df_dategorical_data

NameError: name 'df_dategorical_data' is not defined

In [ ]:
df.columns

In [21]:
df.columns=['a','b','c','d']
df.columns

ValueError: Length mismatch: Expected axis has 5 elements, new values have 4 elements

In [ ]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup', 'mycalc'],
      dtype='object')

In [ ]:
df['CountryCode']

0      ABW
1      AFG
2      AGO
3      ALB
4      ARE
      ...
190    YEM
191    ZAF
192    COD
193    ZMB
194    ZWE
Name: CountryCode, Length: 195, dtype: object

In [ ]:
df["mycalc"]=df.BirthRate*df.InternetUsers
df["mycalc"]

0      808.2516
1      207.9927
2      878.3135
3      736.5644
4      971.8720
         ...
190    658.9400
191    969.5250
192     93.2668
193    623.2534
194    660.7275
Name: mycalc, Length: 195, dtype: float64

In [ ]:
df["InternetUsers"]

0      78.9
1       5.9
2      19.1
3      57.2
4      88.0
       ...
190    20.0
191    46.5
192     2.2
193    15.4
194    18.5
Name: InternetUsers, Length: 195, dtype: float64

In [ ]:
df[["IneternetUsers"]< 2]

TypeError: '<' not supported between instances of 'list' and 'int'

In [ ]:
len(df[df['InternetUsers']< 2])

9

In [ ]:
len(df[df["BirthRate"]> 40])

12

In [ ]:
df[(df]

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (586882450.py, line 1)

In [22]:
df[(df)]

ValueError: Boolean array expected for the condition, not object