In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Pawan', 'Rahul', 'Neha', None],
    'Marks': [85, np.nan, 90, 78],
    'City': ['Pune', 'Mumbai', None, 'Delhi']
}

df = pd.DataFrame(data)
print(df)

    Name  Marks    City
0  Pawan   85.0    Pune
1  Rahul    NaN  Mumbai
2   Neha   90.0    None
3   None   78.0   Delhi

In [8]:
df.isnull()

    Name  Marks   City
0  False  False  False
1  False   True  False
2  False  False   True
3   True  False  False

In [6]:
print(df.isnull())

    Name  Marks   City
0  False  False  False
1  False   True  False
2  False  False   True
3   True  False  False

In [9]:
print(df.isnull().sum())

Name     1
Marks    1
City     1
dtype: int64

In [10]:
df.dropna()

    Name  Marks  City
0  Pawan   85.0  Pune

In [11]:
df

    Name  Marks    City
0  Pawan   85.0    Pune
1  Rahul    NaN  Mumbai
2   Neha   90.0    None
3   None   78.0   Delhi

In [12]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [13]:
df

    Name  Marks    City
0  Pawan   85.0    Pune
1  Rahul    NaN  Mumbai
2   Neha   90.0    None
3   None   78.0   Delhi

In [15]:
df.fillna(1)

    Name  Marks    City
0  Pawan   85.0    Pune
1  Rahul    1.0  Mumbai
2   Neha   90.0       1
3      1   78.0   Delhi

In [16]:
df.fillna(0)

    Name  Marks    City
0  Pawan   85.0    Pune
1  Rahul    0.0  Mumbai
2   Neha   90.0       0
3      0   78.0   Delhi

In [17]:
df

    Name  Marks    City
0  Pawan   85.0    Pune
1  Rahul    NaN  Mumbai
2   Neha   90.0    None
3   None   78.0   Delhi

In [18]:
df.fillna(9)

    Name  Marks    City
0  Pawan   85.0    Pune
1  Rahul    9.0  Mumbai
2   Neha   90.0       9
3      9   78.0   Delhi

In [19]:
df.fillna('Unknown')

      Name    Marks     City
0    Pawan     85.0     Pune
1    Rahul  Unknown   Mumbai
2     Neha     90.0  Unknown
3  Unknown     78.0    Delhi

In [20]:
df['Marks'].fillna(df['Marks'].mean(), inplace=True)

C:\Users\tanpu\AppData\Local\Temp\ipykernel_26208\2710417482.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Marks'].fillna(df['Marks'].mean(), inplace=True)

In [23]:
df.fillna(method='ffill')

C:\Users\tanpu\AppData\Local\Temp\ipykernel_26208\1193302488.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

    Name      Marks    City
0  Pawan  85.000000    Pune
1  Rahul  84.333333  Mumbai
2   Neha  90.000000  Mumbai
3   Neha  78.000000   Delhi

In [24]:
df.fillna(method='bfill')

C:\Users\tanpu\AppData\Local\Temp\ipykernel_26208\2831856154.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')

    Name      Marks    City
0  Pawan  85.000000    Pune
1  Rahul  84.333333  Mumbai
2   Neha  90.000000   Delhi
3   None  78.000000   Delhi