import pandas as pd
#  SERIES

In [2]:
labeled = ['a','b','c']
my_list = [1,2,3,4]

In [3]:
pd.Series(my_list)

0    1
1    2
2    3
3    4
dtype: int64

In [4]:
pd.Series(labeled)

0    a
1    b
2    c
dtype: object

In [15]:

dict = {1:11,2:22,3:33,4:44}
pd.Series(dict)

1    11
2    22
3    33
4    44
dtype: int64

In [6]:
pd.Series(dict)

0    <class 'dict'>
dtype: object

In [10]:
data = {
    "name" : ["pawan","ritesh"],
    "age" :  ["14","20"]
}
pd.Series(data)

name    [pawan, ritesh]
age            [14, 20]
dtype: object

In [8]:
import pandas as pd

data = {
    "name": ["pawan", "ritesh"],
    "age": ["14", "20"]
}

df = pd.Series(data)
print(df)

name    [pawan, ritesh]
age            [14, 20]
dtype: object

  ## DataFrame

In [23]:
data = {
    "name": ['pawan','vaibhav','yogesh'],
    "age" : ['19','20','30'],
    "salary": ['2000','20000','2000000'],
    "city" : ['jalna','vodgao','partur',]
}
pd.DataFrame(data)

      name age   salary    city
0    pawan  19     2000   jalna
1  vaibhav  20    20000  vodgao
2   yogesh  30  2000000  partur

In [17]:
import pandas as pd
data_list = [
    ["pawan",10,2000,'solapur'],
    ["ritesh",12,4000,'partur'],
    [ "vaibhav",23,4000,'jalna'],
    [ "tejas",24,4000,'mantha']
]

df=pd.DataFrame(data_list,columns=["name","age","salary","city"])
df

      name  age  salary     city
0    pawan   10    2000  solapur
1   ritesh   12    4000   partur
2  vaibhav   23    4000    jalna
3    tejas   24    4000   mantha

In [19]:
df["city"]

0    solapur
1     partur
2      jalna
3     mantha
Name: city, dtype: object

In [20]:
df["name"]

0      pawan
1     ritesh
2    vaibhav
3      tejas
Name: name, dtype: object

In [26]:
df["destination"] = ["engg","doctor","farmer","worker"]
df

      name  age  salary     city id destination
0    pawan   10    2000  solapur  1        engg
1   ritesh   12    4000   partur  2      doctor
2  vaibhav   23    4000    jalna  3      farmer
3    tejas   24    4000   mantha  4      worker

In [28]:
df.drop("name",axis=1)

   age  salary     city id destination
0   10    2000  solapur  1        engg
1   12    4000   partur  2      doctor
2   23    4000    jalna  3      farmer
3   24    4000   mantha  4      worker

In [30]:
df.drop("salary",axis=1)

      name  age     city id destination
0    pawan   10  solapur  1        engg
1   ritesh   12   partur  2      doctor
2  vaibhav   23    jalna  3      farmer
3    tejas   24   mantha  4      worker