In [3]:
import pandas as pd

In [7]:
import numpy as np

In [4]:
labels=['a','b','c']
my_list=['10','20','30']

In [5]:
my_list

['10', '20', '30']

In [6]:
labels

['a', 'b', 'c']

In [7]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [8]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: object

In [11]:
labels=['a','b','c','d']
my_list=[10,20,30,40]
arr=np.array([10,20,30])
d={1:10,2:20,3:30}

In [9]:
pd.Series(my_list)

0    10
1    20
2    30
3    40
dtype: int64

In [12]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
d    40
dtype: int64

In [ ]:
arr=[10,20,30,40]
arr

In [13]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [ ]:
d={1:10,2:20,3:30,4:40,5:50,6:60}
d

In [14]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

In [18]:
import pandas as pd

import numpy as np

In [19]:
l=['a','b','c','d','e']
list=[10,20,30,40,50]
arr=np.array([23,24,25,25,26])
d={
    'a':10,'b':20,'c':30,
    'd':40,'e':50
}

In [20]:
pd.Series(l)

0    a
1    b
2    c
3    d
4    e
dtype: object

In [ ]:
import numpy as np

In [21]:
arr=np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [22]:
pd.Series(arr)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [23]:
pd.Series(list)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [25]:
pd.Series(list,index=l)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [ ]:
l=['a','b','c','d','e','f']
l

In [24]:
pd.Series(l)

0    a
1    b
2    c
3    d
4    e
dtype: object

In [26]:
pd.Series(l,index=l)

a    a
b    b
c    c
d    d
e    e
dtype: object

In [ ]:
# Data Frame

In [28]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [29]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [30]:
df['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [31]:
df['City']

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: object

In [32]:
df['Salary']

0    65000
1    70000
2    62000
3    85000
Name: Salary, dtype: int64

In [33]:
d = [
     ['John', 'Anna', 'Peter', 'Linda'],
     [28, 34, 29, 42],
     ['New York', 'Paris', 'Berlin', 'London'],
     [65000, 70000, 62000, 85000]
]
    
    
df = pd.DataFrame(d)

In [34]:
df

          0      1       2       3
0      John   Anna   Peter   Linda
1        28     34      29      42
2  New York  Paris  Berlin  London
3     65000  70000   62000   85000

In [35]:
import pandas as pd

In [23]:
data_list= [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns =columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [36]:
data_list= [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
rows = ["21","22","23","24"]
df2 = pd.DataFrame(data_list,index = rows)
df2

        0   1         2      3
21   John  28  New York  65000
22   Anna  34     Paris  70000
23  Peter  29    Berlin  62000
24  Linda  42    London  85000

In [37]:
data_list= [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
rows = ["a","b","c","d"]
df2 = pd.DataFrame(data_list,index = rows)
df2

       0   1         2      3
a   John  28  New York  65000
b   Anna  34     Paris  70000
c  Peter  29    Berlin  62000
d  Linda  42    London  85000

In [38]:
df2

       0   1         2      3
a   John  28  New York  65000
b   Anna  34     Paris  70000
c  Peter  29    Berlin  62000
d  Linda  42    London  85000

In [39]:
df2

       0   1         2      3
a   John  28  New York  65000
b   Anna  34     Paris  70000
c  Peter  29    Berlin  62000
d  Linda  42    London  85000

In [54]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns =columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [55]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [56]:
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [57]:
df2[['Name','Age']]

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [58]:
df2[['Salary','City']]

   Salary      City
0   65000  New York
1   70000     Paris
2   62000    Berlin
3   85000    London

In [97]:
df2[['Salary', 'City']]

   Salary    City
1   70000   Paris
2   62000  Berlin
3   85000  London

In [59]:
df2['Designation']=['d','e','d','e']
df2['Designation']

0    d
1    e
2    d
3    e
Name: Designation, dtype: object

In [60]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000           d
1   Anna   34     Paris   70000           e
2  Peter   29    Berlin   62000           d
3  Linda   42    London   85000           e

In [61]:
df2["Designation"] = ["Doctor","Eng.","Doctor","Eng."]

In [62]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [63]:
df2["Designation"] = ["Doctor","Eng.","Doctor","Eng."]
df2["Designation"]

0    Doctor
1      Eng.
2    Doctor
3      Eng.
Name: Designation, dtype: object

In [64]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [99]:
df2[['Salary','City']]

   Salary    City
1   70000   Paris
2   62000  Berlin
3   85000  London

In [66]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [67]:
df2.drop(0,axis=0)

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000        Eng.
2  Peter   29  Berlin   62000      Doctor
3  Linda   42  London   85000        Eng.

In [68]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [84]:
df2.drop('Name',axis=1)

KeyError: "['Name'] not found in axis"

In [85]:
df2

   Age    City  Salary Designation
1   34   Paris   70000        Eng.
2   29  Berlin   62000      Doctor
3   42  London   85000        Eng.

In [91]:
df2.drop('Age',axis=1,inplace=True)

KeyError: "['Age'] not found in axis"

In [90]:
df2

     City  Salary Designation
1   Paris   70000        Eng.
2  Berlin   62000      Doctor
3  London   85000        Eng.

In [75]:
df2.loc[0]

Name               John
Age                  28
City           New York
Salary            65000
Designation      Doctor
Name: 0, dtype: object

In [76]:
df2.loc[1]

Name            Anna
Age               34
City           Paris
Salary         70000
Designation     Eng.
Name: 1, dtype: object

In [77]:
df2.loc[2]

Name            Peter
Age                29
City           Berlin
Salary          62000
Designation    Doctor
Name: 2, dtype: object

In [78]:
df2.loc[3]

Name            Linda
Age                42
City           London
Salary          85000
Designation      Eng.
Name: 3, dtype: object

In [109]:
df2.loc[[0,1,2]]

    Name  Age      City  Salary id
0   John   28  New York   65000  1
1   Anna   34     Paris   70000  2
2  Peter   29    Berlin   62000  3

In [110]:
df2.loc[3]

Name       Linda
Age           42
City      London
Salary     85000
id             4
Name: 3, dtype: object

In [111]:
df2.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
id             4
Name: 3, dtype: object

In [112]:
df2.loc[[0,1]][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [79]:
df2[['Salary','City']]

   Salary      City
0   65000  New York
1   70000     Paris
2   62000    Berlin
3   85000    London

In [80]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [81]:
df2.drop(0,axis=0)

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000        Eng.
2  Peter   29  Berlin   62000      Doctor
3  Linda   42  London   85000        Eng.

In [86]:
df2.drop(2,axis=0)

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
3  Linda   42    London   85000        Eng.

In [87]:
df2.drop(1,axis=0)

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [88]:
df2.drop(2,axis=0)

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
3  Linda   42    London   85000        Eng.

In [89]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [90]:
df2.drop(0,axis=0,inplace=True)

In [113]:
df2.drop('Name',axis=1)

   Age      City  Salary id
0   28  New York   65000  1
1   34     Paris   70000  2
2   29    Berlin   62000  3
3   42    London   85000  4

In [91]:
df2

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000        Eng.
2  Peter   29  Berlin   62000      Doctor
3  Linda   42  London   85000        Eng.

In [92]:
df.loc[[1,2]][['Age','City']]

   Age    City
1   34   Paris
2   29  Berlin

In [114]:
df2.loc[1]['Age']

np.int64(34)

In [115]:
df2.loc[2]['Salary']

np.int64(62000)

In [93]:
df2.loc[[2,3]],[['Age','Salary']]

(    Name  Age    City  Salary Designation
 2  Peter   29  Berlin   62000      Doctor
 3  Linda   42  London   85000        Eng.,
 [['Age', 'Salary']])

In [94]:
df2.loc[[2,3]][['Age','Salary']]

   Age  Salary
2   29   62000
3   42   85000

In [95]:
df2['Age']

1    34
2    29
3    42
Name: Age, dtype: int64

In [96]:
df2[(df2['Age']>30)]

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000        Eng.
3  Linda   42  London   85000        Eng.

In [97]:
df2[(df2['Age']<30)]

    Name  Age    City  Salary Designation
2  Peter   29  Berlin   62000      Doctor

In [98]:
df2[(df2['Age']>30)&(df2['City']=='Paris')]

   Name  Age   City  Salary Designation
1  Anna   34  Paris   70000        Eng.

In [104]:
df2['id']=['1','2','3','4']
df2['id']

0    1
1    2
2    3
3    4
Name: id, dtype: object

In [105]:
df2

    Name  Age      City  Salary id
0   John   28  New York   65000  1
1   Anna   34     Paris   70000  2
2  Peter   29    Berlin   62000  3
3  Linda   42    London   85000  4

In [102]:
data_list = [
    ['Pawan', 25, 'Pune', 50000],
    ['Neha', 27, 'Mumbai', 60000],
    ['Amit', 29, 'Delhi', 55000]
]

print(data_list)
df4=pd.DataFrame(data_list)
df4

[['Pawan', 25, 'Pune', 50000], ['Neha', 27, 'Mumbai', 60000], ['Amit', 29, 'Delhi', 55000]]

       0   1       2      3
0  Pawan  25    Pune  50000
1   Neha  27  Mumbai  60000
2   Amit  29   Delhi  55000

In [109]:
data_list = [
    ['Pawan', 25, 'Pune', 50000],
    ['Neha', 27, 'Mumbai', 60000],
    ['Amit', 29, 'Delhi', 55000]
]

print(data_list)
df4=pd.DataFrame(data_list)
df4
columns=['Name','Age','City','Salary']
df5=pd.DataFrame(data_list,columns=columns)
df5

[['Pawan', 25, 'Pune', 50000], ['Neha', 27, 'Mumbai', 60000], ['Amit', 29, 'Delhi', 55000]]

    Name  Age    City  Salary
0  Pawan   25    Pune   50000
1   Neha   27  Mumbai   60000
2   Amit   29   Delhi   55000

In [106]:
df4=pd.DataFrame(data_list)
rows=['a','b','c']
df4=pd.DataFrame(data_list,index=rows)
df4

       0   1       2      3
a  Pawan  25    Pune  50000
b   Neha  27  Mumbai  60000
c   Amit  29   Delhi  55000

In [110]:
df5

    Name  Age    City  Salary
0  Pawan   25    Pune   50000
1   Neha   27  Mumbai   60000
2   Amit   29   Delhi   55000

In [111]:
df5.drop(0,axis=0)

   Name  Age    City  Salary
1  Neha   27  Mumbai   60000
2  Amit   29   Delhi   55000

In [112]:
df5

    Name  Age    City  Salary
0  Pawan   25    Pune   50000
1   Neha   27  Mumbai   60000
2   Amit   29   Delhi   55000

In [113]:
df5.drop(0,axis=0,inplace=True)

In [114]:
df5

   Name  Age    City  Salary
1  Neha   27  Mumbai   60000
2  Amit   29   Delhi   55000

In [115]:
data_list = [
    ['Pawan', 25, 'Pune', 50000],
    ['Neha', 27, 'Mumbai', 60000],
    ['Amit', 29, 'Delhi', 55000]
]

print(data_list)
df8=pd.DataFrame(data_list)
df8

[['Pawan', 25, 'Pune', 50000], ['Neha', 27, 'Mumbai', 60000], ['Amit', 29, 'Delhi', 55000]]

       0   1       2      3
0  Pawan  25    Pune  50000
1   Neha  27  Mumbai  60000
2   Amit  29   Delhi  55000

In [116]:
df8=pd.DataFrame(data_list)
df8
columns=['Name','Age','City','Salary']
df8=pd.DataFrame(data_list,columns=columns)
df8

    Name  Age    City  Salary
0  Pawan   25    Pune   50000
1   Neha   27  Mumbai   60000
2   Amit   29   Delhi   55000

In [117]:
df8.loc[0]

Name      Pawan
Age          25
City       Pune
Salary    50000
Name: 0, dtype: object

In [118]:
df8.loc[[0,1]]

    Name  Age    City  Salary
0  Pawan   25    Pune   50000
1   Neha   27  Mumbai   60000

In [119]:
df8.loc[[1,2]][['City','Salary']]

     City  Salary
1  Mumbai   60000
2   Delhi   55000

In [120]:
df8.loc[[1,2]]

   Name  Age    City  Salary
1  Neha   27  Mumbai   60000
2  Amit   29   Delhi   55000