In [3]:
import pandas as pd

In [3]:
pd.__version__

'2.3.3'

In [4]:
df = pd.read_excel(r"C:\Users\tanpu\Downloads\data.xlsx")
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [5]:
df=pd.read_excel(r"C:\Users\tanpu\Downloads\data.xlsx")
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [6]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [7]:
id(df)

2235639592080

In [8]:
len(df)

195

In [7]:
df.shape

(195, 5)

In [10]:
df.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [11]:
len(df.columns)

5

In [12]:
df.isnull()

     CountryName  CountryCode  BirthRate  InternetUsers  IncomeGroup
0          False        False      False          False        False
1          False        False      False          False        False
2          False        False      False          False        False
3          False        False      False          False        False
4          False        False      False          False        False
..           ...          ...        ...            ...          ...
190        False        False      False          False        False
191        False        False      False          False        False
192        False        False      False          False        False
193        False        False      False          False        False
194        False        False      False          False        False

[195 rows x 5 columns]

In [13]:
df.isna

<bound method DataFrame.isna of               CountryName CountryCode  BirthRate  InternetUsers  \
0                   Aruba         ABW     10.244           78.9
1             Afghanistan         AFG     35.253            5.9
2                  Angola         AGO     45.985           19.1
3                 Albania         ALB     12.877           57.2
4    United Arab Emirates         ARE     11.044           88.0
..                    ...         ...        ...            ...
190           Yemen, Rep.         YEM     32.947           20.0
191          South Africa         ZAF     20.850           46.5
192      Congo, Dem. Rep.         COD     42.394            2.2
193                Zambia         ZMB     40.471           15.4
194              Zimbabwe         ZWE     35.715           18.5

             IncomeGroup
0            High income
1             Low income
2    Upper middle income
3    Upper middle income
4            High income
..                   ...
190  Lower middle income
191  Upper middle income
192           Low income
193  Lower middle income
194           Low income

[195 rows x 5 columns]>

In [14]:
df.isnull().sum()

CountryName      0
CountryCode      0
BirthRate        0
InternetUsers    0
IncomeGroup      0
dtype: int64

In [15]:
df.describe()

        BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800

In [16]:
df.BirthRate*df.InternetUsers

0      808.2516
1      207.9927
2      878.3135
3      736.5644
4      971.8720
         ...
190    658.9400
191    969.5250
192     93.2668
193    623.2534
194    660.7275
Length: 195, dtype: float64

In [8]:
df['InternetUsers']

0      78.9
1       5.9
2      19.1
3      57.2
4      88.0
       ...
190    20.0
191    46.5
192     2.2
193    15.4
194    18.5
Name: InternetUsers, Length: 195, dtype: float64

In [9]:
df['InternetUsers']<2

0      False
1      False
2      False
3      False
4      False
       ...
190    False
191    False
192    False
193    False
194    False
Name: InternetUsers, Length: 195, dtype: bool

In [19]:
df[df['InternetUsers']<2]

      CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
11        Burundi         BDI     44.151            1.3           Low income
52        Eritrea         ERI     34.800            0.9           Low income
55       Ethiopia         ETH     32.925            1.9           Low income
64         Guinea         GIN     37.337            1.6           Low income
117       Myanmar         MMR     18.119            1.6  Lower middle income
127         Niger         NER     49.661            1.7           Low income
154  Sierra Leone         SLE     36.729            1.7           Low income
156       Somalia         SOM     43.891            1.5           Low income
172   Timor-Leste         TLS     35.755            1.1  Lower middle income

In [10]:
df[df['InternetUsers']>2]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [11]:
df[df['InternetUsers']<20]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
11,Burundi,BDI,44.151,1.3,Low income
13,Benin,BEN,36.440,4.9,Low income
14,Burkina Faso,BFA,40.551,9.1,Low income
...,...,...,...,...,...
187,Vanuatu,VUT,26.739,11.3,Lower middle income
189,Samoa,WSM,26.172,15.3,Lower middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [12]:
df[df['InternetUsers']>20]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
5,Argentina,ARG,17.716,59.9,High income
6,Armenia,ARM,13.308,41.9,Lower middle income
...,...,...,...,...,...
184,"Venezuela, RB",VEN,19.842,54.9,High income
185,Virgin Islands (U.S.),VIR,10.700,45.3,High income
186,Vietnam,VNM,15.537,43.9,Lower middle income
188,West Bank and Gaza,PSE,30.394,46.6,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income

In [23]:
len(df[df['InternetUsers']<2])

9

In [13]:
df[(df.BirthRate>40)&(df.InternetUsers<2)]

    CountryName CountryCode  BirthRate  InternetUsers IncomeGroup
11      Burundi         BDI     44.151            1.3  Low income
127       Niger         NER     49.661            1.7  Low income
156     Somalia         SOM     43.891            1.5  Low income

In [14]:
df[(df.BirthRate>4)&(df.InternetUsers<20)]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
11,Burundi,BDI,44.151,1.3,Low income
13,Benin,BEN,36.440,4.9,Low income
14,Burkina Faso,BFA,40.551,9.1,Low income
...,...,...,...,...,...
187,Vanuatu,VUT,26.739,11.3,Lower middle income
189,Samoa,WSM,26.172,15.3,Lower middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [15]:
df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [27]:
df.head()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

In [28]:
df.head(10)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9000,High income
1,Afghanistan,AFG,35.253,5.9000,Low income
2,Angola,AGO,45.985,19.1000,Upper middle income
3,Albania,ALB,12.877,57.2000,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0000,High income
5,Argentina,ARG,17.716,59.9000,High income
6,Armenia,ARM,13.308,41.9000,Lower middle income
7,Antigua and Barbuda,ATG,16.447,63.4000,High income
8,Australia,AUS,13.200,83.0000,High income
9,Austria,AUT,9.400,80.6188,High income

In [29]:
df.head(90)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9000,High income
1,Afghanistan,AFG,35.253,5.9000,Low income
2,Angola,AGO,45.985,19.1000,Upper middle income
3,Albania,ALB,12.877,57.2000,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0000,High income
...,...,...,...,...,...
85,Israel,ISR,21.300,70.8000,High income
86,Italy,ITA,8.500,58.4593,High income
87,Jamaica,JAM,13.540,37.1000,Upper middle income
88,Jordan,JOR,27.046,41.0000,Upper middle income
89,Japan,JPN,8.200,89.7100,High income

In [30]:
df.head(9)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
5,Argentina,ARG,17.716,59.9,High income
6,Armenia,ARM,13.308,41.9,Lower middle income
7,Antigua and Barbuda,ATG,16.447,63.4,High income
8,Australia,AUS,13.200,83.0,High income

In [31]:
df.tail(9)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
186,Vietnam,VNM,15.537,43.9,Lower middle income
187,Vanuatu,VUT,26.739,11.3,Lower middle income
188,West Bank and Gaza,PSE,30.394,46.6,Lower middle income
189,Samoa,WSM,26.172,15.3,Lower middle income
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [32]:
df.tail(90)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
105,Lithuania,LTU,10.100,68.4529,High income
106,Luxembourg,LUX,11.300,93.7765,High income
107,Latvia,LVA,10.200,75.2344,High income
108,"Macao SAR, China",MAC,11.256,65.8000,High income
109,Morocco,MAR,21.023,56.0000,Lower middle income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0000,Lower middle income
191,South Africa,ZAF,20.850,46.5000,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2000,Low income
193,Zambia,ZMB,40.471,15.4000,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5000,Low income

In [16]:
df[1:20]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
1,Afghanistan,AFG,35.253,5.90000,Low income
2,Angola,AGO,45.985,19.10000,Upper middle income
3,Albania,ALB,12.877,57.20000,Upper middle income
4,United Arab Emirates,ARE,11.044,88.00000,High income
5,Argentina,ARG,17.716,59.90000,High income
6,Armenia,ARM,13.308,41.90000,Lower middle income
7,Antigua and Barbuda,ATG,16.447,63.40000,High income
8,Australia,AUS,13.200,83.00000,High income
9,Austria,AUT,9.400,80.61880,High income
10,Azerbaijan,AZE,18.300,58.70000,Upper middle income
11,Burundi,BDI,44.151,1.30000,Low income
12,Belgium,BEL,11.200,82.17020,High income
13,Benin,BEN,36.440,4.90000,Low income
14,Burkina Faso,BFA,40.551,9.10000,Low income
15,Bangladesh,BGD,20.142,6.63000,Lower middle income
16,Bulgaria,BGR,9.200,53.06150,Upper middle income
17,Bahrain,BHR,15.040,90.00004,High income
18,"Bahamas, The",BHS,15.339,72.00000,High income
19,Bosnia and Herzegovina,BIH,9.062,57.79000,Upper middle income

In [17]:
df[9:0]

Empty DataFrame
Columns: [CountryName, CountryCode, BirthRate, InternetUsers, IncomeGroup]
Index: []

In [18]:
df[9:90]

   CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
9      Austria         AUT      9.400        80.6188          High income
10  Azerbaijan         AZE     18.300        58.7000  Upper middle income
11     Burundi         BDI     44.151         1.3000           Low income
12     Belgium         BEL     11.200        82.1702          High income
13       Benin         BEN     36.440         4.9000           Low income
..         ...         ...        ...            ...                  ...
85      Israel         ISR     21.300        70.8000          High income
86       Italy         ITA      8.500        58.4593          High income
87     Jamaica         JAM     13.540        37.1000  Upper middle income
88      Jordan         JOR     27.046        41.0000  Upper middle income
89       Japan         JPN      8.200        89.7100          High income

[81 rows x 5 columns]

In [36]:
df[-1:10]

Empty DataFrame
Columns: [CountryName, CountryCode, BirthRate, InternetUsers, IncomeGroup]
Index: []

In [37]:
df[1:-12]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
1,Afghanistan,AFG,35.253,5.90,Low income
2,Angola,AGO,45.985,19.10,Upper middle income
3,Albania,ALB,12.877,57.20,Upper middle income
4,United Arab Emirates,ARE,11.044,88.00,High income
5,Argentina,ARG,17.716,59.90,High income
...,...,...,...,...,...
178,Uganda,UGA,43.474,16.20,Low income
179,Ukraine,UKR,11.100,41.00,Lower middle income
180,Uruguay,URY,14.374,57.69,High income
181,United States,USA,12.500,84.20,High income
182,Uzbekistan,UZB,22.500,38.20,Lower middle income

In [38]:
df[1:4]

   CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
1  Afghanistan         AFG     35.253            5.9           Low income
2       Angola         AGO     45.985           19.1  Upper middle income
3      Albania         ALB     12.877           57.2  Upper middle income

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryName    195 non-null    object
 1   CountryCode    195 non-null    object
 2   BirthRate      195 non-null    float64
 3   InternetUsers  195 non-null    float64
 4   IncomeGroup    195 non-null    object
dtypes: float64(2), object(3)
memory usage: 7.7+ KB

In [40]:
import pandas as pd

In [19]:
df2=pd.read_excel(r'C:\Users\tanpu\Downloads\data.xlsx')
df2

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [20]:
df2

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [21]:
df2['CountryName']

0                     Aruba
1               Afghanistan
2                    Angola
3                   Albania
4      United Arab Emirates
               ...
190             Yemen, Rep.
191            South Africa
192        Congo, Dem. Rep.
193                  Zambia
194                Zimbabwe
Name: CountryName, Length: 195, dtype: object

In [22]:
id(df2)

1783352198992

In [23]:
pd.__version__

'2.3.3'

In [24]:
pd.__version

AttributeError: module 'pandas' has no attribute '__version'

In [25]:
len(df2)

195

In [26]:
df2

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [58]:
df2.head()

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

In [27]:
df2.head(3)

   CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0        Aruba         ABW     10.244           78.9          High income
1  Afghanistan         AFG     35.253            5.9           Low income
2       Angola         AGO     45.985           19.1  Upper middle income

In [28]:
df2.head(4)

   CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0        Aruba         ABW     10.244           78.9          High income
1  Afghanistan         AFG     35.253            5.9           Low income
2       Angola         AGO     45.985           19.1  Upper middle income
3      Albania         ALB     12.877           57.2  Upper middle income

df2.head(5)

In [29]:
df2.head(6)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
5,Argentina,ARG,17.716,59.9,High income

In [30]:
df2.head(7)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
5,Argentina,ARG,17.716,59.9,High income
6,Armenia,ARM,13.308,41.9,Lower middle income

In [31]:
df2.head(9)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
5,Argentina,ARG,17.716,59.9,High income
6,Armenia,ARM,13.308,41.9,Lower middle income
7,Antigua and Barbuda,ATG,16.447,63.4,High income
8,Australia,AUS,13.200,83.0,High income

In [59]:
df2.tail(4)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [32]:
df2.tail(9)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
186,Vietnam,VNM,15.537,43.9,Lower middle income
187,Vanuatu,VUT,26.739,11.3,Lower middle income
188,West Bank and Gaza,PSE,30.394,46.6,Lower middle income
189,Samoa,WSM,26.172,15.3,Lower middle income
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [33]:
df2.tail(3)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [34]:
df2.tail(4)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [35]:
df2.tail(5)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [36]:
df2.tail(6)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
189,Samoa,WSM,26.172,15.3,Lower middle income
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [37]:
df2.tail(8)

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
187,Vanuatu,VUT,26.739,11.3,Lower middle income
188,West Bank and Gaza,PSE,30.394,46.6,Lower middle income
189,Samoa,WSM,26.172,15.3,Lower middle income
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [38]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryName    195 non-null    object
 1   CountryCode    195 non-null    object
 2   BirthRate      195 non-null    float64
 3   InternetUsers  195 non-null    float64
 4   IncomeGroup    195 non-null    object
dtypes: float64(2), object(3)
memory usage: 7.7+ KB

In [62]:
df2.columns

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [61]:
len(df2.columns)

5

In [ ]:
df2.dtypes

In [64]:
df2['CountryName']

0                     Aruba
1               Afghanistan
2                    Angola
3                   Albania
4      United Arab Emirates
               ...
190             Yemen, Rep.
191            South Africa
192        Congo, Dem. Rep.
193                  Zambia
194                Zimbabwe
Name: CountryName, Length: 195, dtype: object

In [65]:
df2["CountryCode"]

0      ABW
1      AFG
2      AGO
3      ALB
4      ARE
      ...
190    YEM
191    ZAF
192    COD
193    ZMB
194    ZWE
Name: CountryCode, Length: 195, dtype: object

In [ ]:
df2.dtypes

In [ ]:
df2

In [66]:
df2[['BirthRate','InternetUsers']]

     BirthRate  InternetUsers
0       10.244           78.9
1       35.253            5.9
2       45.985           19.1
3       12.877           57.2
4       11.044           88.0
..         ...            ...
190     32.947           20.0
191     20.850           46.5
192     42.394            2.2
193     40.471           15.4
194     35.715           18.5

[195 rows x 2 columns]

In [67]:
df2['InternetUsers']

0      78.9
1       5.9
2      19.1
3      57.2
4      88.0
       ...
190    20.0
191    46.5
192     2.2
193    15.4
194    18.5
Name: InternetUsers, Length: 195, dtype: float64

In [39]:
df2['BirthRate']

0      10.244
1      35.253
2      45.985
3      12.877
4      11.044
        ...
190    32.947
191    20.850
192    42.394
193    40.471
194    35.715
Name: BirthRate, Length: 195, dtype: float64

In [68]:
df2['CountryCode']

0      ABW
1      AFG
2      AGO
3      ALB
4      ARE
      ...
190    YEM
191    ZAF
192    COD
193    ZMB
194    ZWE
Name: CountryCode, Length: 195, dtype: object

In [69]:
df2[['BirthRate','InternetUsers']]

     BirthRate  InternetUsers
0       10.244           78.9
1       35.253            5.9
2       45.985           19.1
3       12.877           57.2
4       11.044           88.0
..         ...            ...
190     32.947           20.0
191     20.850           46.5
192     42.394            2.2
193     40.471           15.4
194     35.715           18.5

[195 rows x 2 columns]

In [70]:
df2_numerical_data=df2[['BirthRate','InternetUsers']]
df2_numerical_data

     BirthRate  InternetUsers
0       10.244           78.9
1       35.253            5.9
2       45.985           19.1
3       12.877           57.2
4       11.044           88.0
..         ...            ...
190     32.947           20.0
191     20.850           46.5
192     42.394            2.2
193     40.471           15.4
194     35.715           18.5

[195 rows x 2 columns]

In [43]:
df2_numerical_data=df2[['BirthRate','InternetUsers']]
df2_numerical_data
df2_categorical_data=df2[['CountryName','CountryCode','IncomeGroup']]
df2_categorical_data

              CountryName CountryCode          IncomeGroup
0                   Aruba         ABW          High income
1             Afghanistan         AFG           Low income
2                  Angola         AGO  Upper middle income
3                 Albania         ALB  Upper middle income
4    United Arab Emirates         ARE          High income
..                    ...         ...                  ...
190           Yemen, Rep.         YEM  Lower middle income
191          South Africa         ZAF  Upper middle income
192      Congo, Dem. Rep.         COD           Low income
193                Zambia         ZMB  Lower middle income
194              Zimbabwe         ZWE           Low income

[195 rows x 3 columns]

In [44]:
df2_categorical_data.head(4)

   CountryName CountryCode          IncomeGroup
0        Aruba         ABW          High income
1  Afghanistan         AFG           Low income
2       Angola         AGO  Upper middle income
3      Albania         ALB  Upper middle income

In [45]:
df2_categorical_data.tail(4)

          CountryName CountryCode          IncomeGroup
191      South Africa         ZAF  Upper middle income
192  Congo, Dem. Rep.         COD           Low income
193            Zambia         ZMB  Lower middle income
194          Zimbabwe         ZWE           Low income

In [46]:
df2_numerical_data.tail(9)

     BirthRate  InternetUsers
186     15.537           43.9
187     26.739           11.3
188     30.394           46.6
189     26.172           15.3
190     32.947           20.0
191     20.850           46.5
192     42.394            2.2
193     40.471           15.4
194     35.715           18.5

In [47]:
df2_numerical_data.head(3)

   BirthRate  InternetUsers
0     10.244           78.9
1     35.253            5.9
2     45.985           19.1

In [48]:
df2_categorical_data.head(4)

   CountryName CountryCode          IncomeGroup
0        Aruba         ABW          High income
1  Afghanistan         AFG           Low income
2       Angola         AGO  Upper middle income
3      Albania         ALB  Upper middle income

In [49]:
df2_numerical_data.tail(4)

     BirthRate  InternetUsers
191     20.850           46.5
192     42.394            2.2
193     40.471           15.4
194     35.715           18.5

In [50]:
df2_categorical_data.head(4)

   CountryName CountryCode          IncomeGroup
0        Aruba         ABW          High income
1  Afghanistan         AFG           Low income
2       Angola         AGO  Upper middle income
3      Albania         ALB  Upper middle income

In [51]:
df2

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [52]:
df2.shape

(195, 5)

In [53]:
df2_numerical_data.shape

(195, 2)

In [54]:
df2_categorical_data.shape

(195, 3)

In [55]:
df2_numerical_data.columns

Index(['BirthRate', 'InternetUsers'], dtype='object')

In [56]:
df2_categorical_data.columns

Index(['CountryName', 'CountryCode', 'IncomeGroup'], dtype='object')

In [57]:
df2_categorical_data.rows

AttributeError: 'DataFrame' object has no attribute 'rows'

In [58]:
df2

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [59]:
df2.BirthRate*InternetUsers

NameError: name 'InternetUsers' is not defined

In [76]:
df2.BirthRate*df2.InternetUsers

0      808.2516
1      207.9927
2      878.3135
3      736.5644
4      971.8720
         ...
190    658.9400
191    969.5250
192     93.2668
193    623.2534
194    660.7275
Length: 195, dtype: float64

In [60]:
df2.CountryName*df2.CountryCode

TypeError: can't multiply sequence by non-int of type 'str'

In [61]:
df2

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [62]:
df2[:]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [72]:
df2[1:4]

   CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
1  Afghanistan         AFG     35.253            5.9           Low income
2       Angola         AGO     45.985           19.1  Upper middle income
3      Albania         ALB     12.877           57.2  Upper middle income

In [63]:
df2[10:11]

   CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
10  Azerbaijan         AZE       18.3           58.7  Upper middle income

In [64]:
df2[1:94:10]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
1,Afghanistan,AFG,35.253,5.9000,Low income
11,Burundi,BDI,44.151,1.3000,Low income
21,Belize,BLZ,23.092,33.6000,Upper middle income
31,Switzerland,CHE,10.200,86.3400,High income
41,Cuba,CUB,10.400,27.9300,Upper middle income
51,"Egypt, Arab Rep.",EGY,28.032,29.4000,Lower middle income
61,United Kingdom,GBR,12.200,89.8441,High income
71,Guatemala,GTM,27.465,19.7000,Lower middle income
81,Ireland,IRL,15.000,78.2477,High income
91,Kenya,KEN,35.194,39.0000,Lower middle income

In [65]:
df2[1:94:5]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
1,Afghanistan,AFG,35.253,5.9000,Low income
6,Armenia,ARM,13.308,41.9000,Lower middle income
11,Burundi,BDI,44.151,1.3000,Low income
16,Bulgaria,BGR,9.200,53.0615,Upper middle income
21,Belize,BLZ,23.092,33.6000,Upper middle income
26,Brunei Darussalam,BRN,16.405,64.5000,High income
31,Switzerland,CHE,10.200,86.3400,High income
36,"Congo, Rep.",COG,37.011,6.6000,Lower middle income
41,Cuba,CUB,10.400,27.9300,Upper middle income
46,Djibouti,DJI,25.486,9.5000,Lower middle income
51,"Egypt, Arab Rep.",EGY,28.032,29.4000,Lower middle income
56,Finland,FIN,10.700,91.5144,High income
61,United Kingdom,GBR,12.200,89.8441,High income
66,Guinea-Bissau,GNB,37.503,3.1000,Low income
71,Guatemala,GTM,27.465,19.7000,Lower middle income
76,Croatia,HRV,9.400,66.7476,High income
81,Ireland,IRL,15.000,78.2477,High income
86,Italy,ITA,8.500,58.4593,High income
91,Kenya,KEN,35.194,39.0000,Lower middle income

In [66]:
df2[20:90:7]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
20,Belarus,BLR,12.500,54.1700,Upper middle income
27,Bhutan,BTN,18.134,29.9000,Lower middle income
34,Cote d'Ivoire,CIV,37.320,8.4000,Lower middle income
41,Cuba,CUB,10.400,27.9300,Upper middle income
48,Dominican Republic,DOM,21.198,45.9000,Upper middle income
55,Ethiopia,ETH,32.925,1.9000,Low income
62,Georgia,GEO,13.332,43.3000,Lower middle income
69,Grenada,GRD,19.334,35.0000,Upper middle income
76,Croatia,HRV,9.400,66.7476,High income
83,Iraq,IRQ,31.093,9.2000,Upper middle income

In [67]:
df2[3:30:3]

     CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
3        Albania         ALB     12.877        57.2000  Upper middle income
6        Armenia         ARM     13.308        41.9000  Lower middle income
9        Austria         AUT      9.400        80.6188          High income
12       Belgium         BEL     11.200        82.1702          High income
15    Bangladesh         BGD     20.142         6.6300  Lower middle income
18  Bahamas, The         BHS     15.339        72.0000          High income
21        Belize         BLZ     23.092        33.6000  Upper middle income
24        Brazil         BRA     14.931        51.0400  Upper middle income
27        Bhutan         BTN     18.134        29.9000  Lower middle income

In [68]:
df2[10:1]

Empty DataFrame
Columns: [CountryName, CountryCode, BirthRate, InternetUsers, IncomeGroup]
Index: []

In [69]:
df2[70:10:5]

Empty DataFrame
Columns: [CountryName, CountryCode, BirthRate, InternetUsers, IncomeGroup]
Index: []

In [70]:
df2[40:60:12]

   CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
40  Costa Rica         CRI     15.022          45.96  Upper middle income
52     Eritrea         ERI     34.800           0.90           Low income

In [71]:
df2[30:50:10]

   CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
30      Canada         CAN     10.900          85.80          High income
40  Costa Rica         CRI     15.022          45.96  Upper middle income

In [72]:
df2[::2]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
2,Angola,AGO,45.985,19.1,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
6,Armenia,ARM,13.308,41.9,Lower middle income
8,Australia,AUS,13.200,83.0,High income
...,...,...,...,...,...
186,Vietnam,VNM,15.537,43.9,Lower middle income
188,West Bank and Gaza,PSE,30.394,46.6,Lower middle income
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [73]:
df2[::1]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [74]:
df2[::3]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9000,High income
3,Albania,ALB,12.877,57.2000,Upper middle income
6,Armenia,ARM,13.308,41.9000,Lower middle income
9,Austria,AUT,9.400,80.6188,High income
12,Belgium,BEL,11.200,82.1702,High income
...,...,...,...,...,...
180,Uruguay,URY,14.374,57.6900,High income
183,St. Vincent and the Grenadines,VCT,16.306,52.0000,Upper middle income
186,Vietnam,VNM,15.537,43.9000,Lower middle income
189,Samoa,WSM,26.172,15.3000,Lower middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2000,Low income

In [75]:
df2[::5]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.900000,High income
5,Argentina,ARG,17.716,59.900000,High income
10,Azerbaijan,AZE,18.300,58.700000,Upper middle income
15,Bangladesh,BGD,20.142,6.630000,Lower middle income
20,Belarus,BLR,12.500,54.170000,Upper middle income
25,Barbados,BRB,12.188,73.000000,High income
30,Canada,CAN,10.900,85.800000,High income
35,Cameroon,CMR,37.236,6.400000,Lower middle income
40,Costa Rica,CRI,15.022,45.960000,Upper middle income
45,Germany,DEU,8.500,84.170000,High income
50,Ecuador,ECU,21.070,40.353684,Upper middle income
55,Ethiopia,ETH,32.925,1.900000,Low income
60,Gabon,GAB,30.555,9.200000,Upper middle income
65,"Gambia, The",GMB,42.525,14.000000,Low income
70,Greenland,GRL,14.500,65.800000,High income
75,Honduras,HND,21.593,17.800000,Lower middle income
80,India,IND,20.291,15.100000,Lower middle income
85,Israel,ISR,21.300,70.800000,High income
90,Kazakhstan,KAZ,22.730,54.000000,Upper middle income
95,"Korea, Rep.",KOR,8.600,84.770000,High income
100,Libya,LBY,21.425,16.500000,Upper middle income
105,Lithuania,LTU,10.100,68.452900,High income
110,Moldova,MDA,12.141,45.000000,Lower middle income
115,Mali,MLI,44.138,3.500000,Low income
120,Mozambique,MOZ,39.705,5.400000,Low income
125,Namibia,NAM,29.937,13.900000,Upper middle income
130,Netherlands,NLD,10.200,93.956400,High income
135,Pakistan,PAK,29.582,10.900000,Lower middle income
140,Poland,POL,9.600,62.849200,High income
145,Qatar,QAT,11.940,85.300000,High income
150,Sudan,SDN,33.477,22.700000,Lower middle income
155,El Salvador,SLV,17.476,23.109300,Lower middle income
160,Suriname,SUR,18.455,37.400000,Upper middle income
165,Seychelles,SYC,18.600,50.400000,High income
170,Tajikistan,TJK,30.792,16.000000,Lower middle income
175,Tunisia,TUN,19.800,43.800000,Upper middle income
180,Uruguay,URY,14.374,57.690000,High income
185,Virgin Islands (U.S.),VIR,10.700,45.300000,High income
190,"Yemen, Rep.",YEM,32.947,20.000000,Lower middle income

In [76]:
df2[::10]

     CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0          Aruba         ABW     10.244      78.900000          High income
10    Azerbaijan         AZE     18.300      58.700000  Upper middle income
20       Belarus         BLR     12.500      54.170000  Upper middle income
30        Canada         CAN     10.900      85.800000          High income
40    Costa Rica         CRI     15.022      45.960000  Upper middle income
50       Ecuador         ECU     21.070      40.353684  Upper middle income
60         Gabon         GAB     30.555       9.200000  Upper middle income
70     Greenland         GRL     14.500      65.800000          High income
80         India         IND     20.291      15.100000  Lower middle income
90    Kazakhstan         KAZ     22.730      54.000000  Upper middle income
100        Libya         LBY     21.425      16.500000  Upper middle income
110      Moldova         MDA     12.141      45.000000  Lower middle income
120   Mozambique         MOZ     39.705       5.400000           Low income
130  Netherlands         NLD     10.200      93.956400          High income
140       Poland         POL      9.600      62.849200          High income
150        Sudan         SDN     33.477      22.700000  Lower middle income
160     Suriname         SUR     18.455      37.400000  Upper middle income
170   Tajikistan         TJK     30.792      16.000000  Lower middle income
180      Uruguay         URY     14.374      57.690000          High income
190  Yemen, Rep.         YEM     32.947      20.000000  Lower middle income

In [77]:
df2[::-2]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
194,Zimbabwe,ZWE,35.715,18.5,Low income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
188,West Bank and Gaza,PSE,30.394,46.6,Lower middle income
186,Vietnam,VNM,15.537,43.9,Lower middle income
...,...,...,...,...,...
8,Australia,AUS,13.200,83.0,High income
6,Armenia,ARM,13.308,41.9,Lower middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
2,Angola,AGO,45.985,19.1,Upper middle income
0,Aruba,ABW,10.244,78.9,High income

In [52]:
df2.isna()

     CountryName  CountryCode  BirthRate  InternetUsers  IncomeGroup
0          False        False      False          False        False
1          False        False      False          False        False
2          False        False      False          False        False
3          False        False      False          False        False
4          False        False      False          False        False
..           ...          ...        ...            ...          ...
190        False        False      False          False        False
191        False        False      False          False        False
192        False        False      False          False        False
193        False        False      False          False        False
194        False        False      False          False        False

[195 rows x 5 columns]

In [78]:
df2.isnull()

     CountryName  CountryCode  BirthRate  InternetUsers  IncomeGroup
0          False        False      False          False        False
1          False        False      False          False        False
2          False        False      False          False        False
3          False        False      False          False        False
4          False        False      False          False        False
..           ...          ...        ...            ...          ...
190        False        False      False          False        False
191        False        False      False          False        False
192        False        False      False          False        False
193        False        False      False          False        False
194        False        False      False          False        False

[195 rows x 5 columns]

In [79]:
df2.isnull().sum()

CountryName      0
CountryCode      0
BirthRate        0
InternetUsers    0
IncomeGroup      0
dtype: int64

In [80]:
df2.isna().sum()

CountryName      0
CountryCode      0
BirthRate        0
InternetUsers    0
IncomeGroup      0
dtype: int64

In [81]:
df2.describe()

        BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800

In [82]:
df2.max()

CountryName                 Zimbabwe
CountryCode                      ZWE
BirthRate                     49.661
InternetUsers                96.5468
IncomeGroup      Upper middle income
dtype: object

In [49]:
df2.min()

CountryName      Afghanistan
CountryCode              ABW
BirthRate                7.9
InternetUsers            0.9
IncomeGroup      High income
dtype: object

In [54]:
df2

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [83]:
df2_categorical_data.describe()

       CountryName CountryCode  IncomeGroup
count          195         195          195
unique         195         195            4
top          Aruba         ABW  High income
freq             1           1           67

In [84]:
df2_numerical_data.describe()

        BirthRate  InternetUsers
count  195.000000     195.000000
mean    21.469928      42.076471
std     10.605467      29.030788
min      7.900000       0.900000
25%     12.120500      14.520000
50%     19.680000      41.000000
75%     29.759500      66.225000
max     49.661000      96.546800

In [47]:
df2.BirthRate*df2.InternetUsers

0      808.2516
1      207.9927
2      878.3135
3      736.5644
4      971.8720
         ...
190    658.9400
191    969.5250
192     93.2668
193    623.2534
194    660.7275
Length: 195, dtype: float64

In [79]:
df2[10:16]

     CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
10    Azerbaijan         AZE     18.300        58.7000  Upper middle income
11       Burundi         BDI     44.151         1.3000           Low income
12       Belgium         BEL     11.200        82.1702          High income
13         Benin         BEN     36.440         4.9000           Low income
14  Burkina Faso         BFA     40.551         9.1000           Low income
15    Bangladesh         BGD     20.142         6.6300  Lower middle income

In [80]:
df2[40:44]

       CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
40      Costa Rica         CRI     15.022        45.9600  Upper middle income
41            Cuba         CUB     10.400        27.9300  Upper middle income
42  Cayman Islands         CYM     12.500        74.1000          High income
43          Cyprus         CYP     11.436        65.4548          High income

In [81]:
df2[::3]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9000,High income
3,Albania,ALB,12.877,57.2000,Upper middle income
6,Armenia,ARM,13.308,41.9000,Lower middle income
9,Austria,AUT,9.400,80.6188,High income
12,Belgium,BEL,11.200,82.1702,High income
...,...,...,...,...,...
180,Uruguay,URY,14.374,57.6900,High income
183,St. Vincent and the Grenadines,VCT,16.306,52.0000,Upper middle income
186,Vietnam,VNM,15.537,43.9000,Lower middle income
189,Samoa,WSM,26.172,15.3000,Lower middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2000,Low income

In [82]:
df[df['InternetUsers']<2]

      CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
11        Burundi         BDI     44.151            1.3           Low income
52        Eritrea         ERI     34.800            0.9           Low income
55       Ethiopia         ETH     32.925            1.9           Low income
64         Guinea         GIN     37.337            1.6           Low income
117       Myanmar         MMR     18.119            1.6  Lower middle income
127         Niger         NER     49.661            1.7           Low income
154  Sierra Leone         SLE     36.729            1.7           Low income
156       Somalia         SOM     43.891            1.5           Low income
172   Timor-Leste         TLS     35.755            1.1  Lower middle income

In [83]:
df2[df2['InternetUsers']<1]

   CountryName CountryCode  BirthRate  InternetUsers IncomeGroup
52     Eritrea         ERI       34.8            0.9  Low income

In [84]:
df2[df2['BirthRate']>3]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [85]:
df2[df2['BirthRate']<40.342]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
5,Argentina,ARG,17.716,59.9,High income
...,...,...,...,...,...
188,West Bank and Gaza,PSE,30.394,46.6,Lower middle income
189,Samoa,WSM,26.172,15.3,Lower middle income
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [87]:
df2[df2['InternetUsers']<4]

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
11,Burundi,BDI,44.151,1.3,Low income
29,Central African Republic,CAF,34.076,3.5,Low income
52,Eritrea,ERI,34.800,0.9,Low income
55,Ethiopia,ETH,32.925,1.9,Low income
64,Guinea,GIN,37.337,1.6,Low income
66,Guinea-Bissau,GNB,37.503,3.1,Low income
99,Liberia,LBR,35.521,3.2,Low income
111,Madagascar,MDG,34.686,3.0,Low income
115,Mali,MLI,44.138,3.5,Low income
117,Myanmar,MMR,18.119,1.6,Lower middle income
127,Niger,NER,49.661,1.7,Low income
154,Sierra Leone,SLE,36.729,1.7,Low income
156,Somalia,SOM,43.891,1.5,Low income
167,Chad,TCD,45.745,2.3,Low income
172,Timor-Leste,TLS,35.755,1.1,Lower middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income