In [2]:
import pandas as pd

In [5]:
import numpy as np

In [6]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [7]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [14]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [8]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [9]:
df.isnull()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [11]:
df.fillna(7)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  7.0
2  7.0  3  3.0  7.0
3  4.0  4  7.0  7.0
4  5.0  5  7.0  5.0

In [12]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [13]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [15]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [19]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [21]:
p=df.fillna(9)
p

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  9.0
2  9.0  3  3.0  9.0
3  4.0  4  9.0  9.0
4  5.0  5  9.0  5.0

In [24]:
p.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  9.0
2  9.0  3  3.0  9.0
3  4.0  4  9.0  9.0
4  5.0  5  9.0  5.0

In [25]:
df.dropna(thresh=1)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [26]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [27]:
df.fillna(8)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  8.0
2  8.0  3  3.0  8.0
3  4.0  4  8.0  8.0
4  5.0  5  8.0  5.0

In [30]:
values={'A':0,'B':100,'C':200,'D':300}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  300.0
2  0.0  3    3.0  300.0
3  4.0  4  200.0  300.0
4  5.0  5  200.0    5.0

In [34]:
values={'A':'pawan','B':'anna','C':'ravi','D':'shiv'}
df.fillna(value=values)

       A  B     C     D
0    1.0  1   1.0   1.0
1    2.0  2   2.0  shiv
2  pawan  3   3.0  shiv
3    4.0  4  ravi  shiv
4    5.0  5  ravi   5.0

In [35]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

In [36]:
df.fillna(df.max())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  5.0
2  5.0  3  3.0  5.0
3  4.0  4  3.0  5.0
4  5.0  5  3.0  5.0